apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd.yaml
- deployment.yaml
- service.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml

commonLabels:
  app: micro-fe
