apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: micro-fe-sample

resources: 
- ../../base
- ../../../applications/profile-uic/base

patches: 
  - patches/ufe-controller.service.yaml
  - patches/ufe-controller.deployment.yaml
